### ISSUE TITLE
golang panic: runtime error

### ISSUE THREAD

**Issue by DasX** [R4yGM/dorkscout#1]
Hej, im using go version go1.16.8 linux/amd64.

When trying to run a scan (installing wordlists worked fine) im running into several runtime errors almost instant.

./dorkscout scan --OutputHTML "dorks" --dorklist "dorks/Advisories and Vulnerabilities.dorkscout" --target www.#####.###

Started scanning ##### with dorks/Advisories and Vulnerabilities.dorkscout
88
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x59f1c0]

goroutine 1 [running]:
text/template.errRecover(0xc0001c95d8)
        /usr/local/go/src/text/template/exec.go:163 +0x1b2
panic(0x99c2c0, 0xebf790)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
text/template.(*Template).execute(0x0, 0xaf5a80, 0x0, 0x996920, 0xc000233b60, 0x0, 0x0)
        /usr/local/go/src/text/template/exec.go:217 +0x180
text/template.(*Template).Execute(...)
        /usr/local/go/src/text/template/exec.go:203
github.com/R4yGM/dorkscout/results.HTMLInject(0x7fff0527616c, 0x2e, 0xc0001c9b00, 0xa46451, 0xa, 0x7fff0527615b, 0x5, 0x0)
        /usr/local/go/src/github.com/R4yGM/dorkscout/results/results.go:257 +0x10ef
github.com/R4yGM/dorkscout/cmd.scan(0x0)
        /usr/local/go/src/github.com/R4yGM/dorkscout/cmd/scan.go:102 +0x1378
github.com/R4yGM/dorkscout/cmd.google_scan()
        /usr/local/go/src/github.com/R4yGM/dorkscout/cmd/scan.go:244 +0x2f4
github.com/R4yGM/dorkscout/cmd.glob..func3(0xecc3c0, 0xc000070ae0, 0x0, 0x6)
        /usr/local/go/src/github.com/R4yGM/dorkscout/cmd/scan.go:51 +0x53
github.com/spf13/cobra.(*Command).execute(0xecc3c0, 0xc000070a80, 0x6, 0x6, 0xecc3c0, 0xc000070a80)
        /mnt/c/Users/rayan/documents/GOLANG/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xecc140, 0x0, 0xffffffff, 0xc00007c058)
        /mnt/c/Users/rayan/documents/GOLANG/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /mnt/c/Users/rayan/documents/GOLANG/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/R4yGM/dorkscout/cmd.Execute(...)
        /usr/local/go/src/github.com/R4yGM/dorkscout/cmd/root.go:14
main.main()
        /usr/local/go/src/github.com/R4yGM/dorkscout/main.go:6 +0x2d

**Comment by R4yGM** [comment]
i ran the same command and it was working for me, it looks like that your dorkscout can't write the html results, try to update dorkscout or check if it has enough permissions to write files
